my classmates usually get up of class inglish at 16:00 and return to their homes


airport
destination
trip



ranch
country
s


abcaa

1G2B3A7CBB

Who was rene Favaloro?
He was a doctor 

What was the weather like yesterday?
it was cold

was is hot yesterday?
No, it wasn´t

were your parents born in brasil?
NO, they weren´t

Who was our president in 2017?
he was Lenin moerno

Who was Fredy mercury?
He was a famous singer