name: Access Domain - DockerHub

on:
  push:
    paths:
      - "access-domain/**"
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Entry Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/entry-service:latest ./access-domain/entry-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/entry-service:latest

      - name: Build & Push Exit Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/exit-service:latest ./access-domain/exit-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/exit-service:latest
