name: Billing Domain - DockerHub

on:
  push:
    paths:
      - "billing-domain/**"
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Billing Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/billing-service:latest ./billing-domain/billing-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/billing-service:latest

      - name: Build & Push Notification Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest ./billing-domain/notification-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
