name: Parking Domain - DockerHub

on:
  push:
    paths:
      - "parking-domain/**"
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Parking Space Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/parking-space-service:latest ./parking-domain/parking-space-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/parking-space-service:latest

      - name: Build & Push Parking Lot Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/parking-lot-service:latest ./parking-domain/parking-lot-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/parking-lot-service:latest
