name: Security Domain - DockerHub

on:
  push:
    paths:
      - "security-domain/**"
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest ./security-domain/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build & Push User Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./security-domain/user-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
