name: Vehicle Domain - DockerHub

on:
  push:
    branches: [ "main" ]
    paths:
      - "services/vehicle/**"
      - "turbo.json"
      - "package.json"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Turborepo)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Turbo build (vehicle domain)
        run: npx turbo run build --filter=vehicle...

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Vehicle Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-service:latest ./services/vehicle/vehicle-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-service:latest
